export const CONNECT_TO_CHAT = 'CONNECT_TO_CHAT';
export const CONNECT_TO_CHAT_SUCCESS = 'CONNECT_TO_CHAT_SUCCESS';
export const CONNECT_TO_CHAT_FAIL = 'CONNECT_TO_CHAT_FAIL';

export const FETCH_LATEST_MESSAGES = 'FETCH_LATEST_MESSAGES';
export const FETCH_MORE_MESSAGES = 'FETCH_MORE_MESSAGES';

export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
